# Generated by Django 5.2.9 on 2026-01-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='booking_agency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='actors.bookingagency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='carrier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='actors.carrier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='actors.customer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customs_agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='actors.customsagent'),
        ),
    ]
