# Generated by Django 5.2.9 on 2026-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_booking_agency_customuser_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('booking_agency', 'Booking Agency'), ('carrier', 'Carrier'), ('customs_agent', 'Customs Agent')], max_length=50, null=True),
        ),
    ]
