# Generated by Django 5.2.9 on 2026-01-12 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('crm', '0001_initial'),
        ('master', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='converted_shipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='salesman',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='shipper',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationdocument',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalquotationdocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationdocument',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationnote',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalquotationnote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationnote',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='mass_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.unitofmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='package_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.unitofmeasurementlength'),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='historicalleadfollowup',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='historicalleadactivity',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='charge_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_quotations', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignee_quotations', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_quotation', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipper_quotations', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquotationpackage',
            name='quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='historicalquotationnote',
            name='quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='historicalquotationdocument',
            name='quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationchargeline',
            name='applied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='quotationchargeline',
            name='charge_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotationchargeline',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotationchargeline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_lines', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationcostline',
            name='applied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='quotationcostline',
            name='charge_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotationcostline',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='quotationcostline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationdocument',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='quotationdocument',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationdocument',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationnote',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='quotationnote',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationnote',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationpackage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='quotationpackage',
            name='mass_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_pkg_unit_mass', to='master.unitofmeasurement'),
        ),
        migrations.AddField(
            model_name='quotationpackage',
            name='package_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_pkg_unit_length', to='master.unitofmeasurementlength'),
        ),
        migrations.AddField(
            model_name='quotationpackage',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationpackage',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['branch', 'name'], name='crm_contact_branch__46ca76_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['branch', 'code'], name='crm_contact_branch__8733df_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_contactgroup_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code__isnull', True), _negated=True), models.Q(('code', ''), _negated=True)), fields=('branch', 'code'), name='uq_contactgroup_branch_code'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['branch', 'name'], name='crm_contact_branch__4e4369_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['branch', 'email'], name='crm_contact_branch__83eab2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['branch', 'phone'], name='crm_contact_branch__2efd90_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['branch', 'type'], name='crm_contact_branch__22190f_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code__isnull', True), _negated=True), models.Q(('code', ''), _negated=True)), fields=('branch', 'code'), name='uq_contact_branch_code'),
        ),
    ]
