# Generated by Django 5.2.9 on 2026-01-15 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('crm', '0002_initial'),
        ('master', '0001_initial'),
        ('operations', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcharges',
            name='sales_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_shipment_charge', to='sales.salesitem'),
        ),
        migrations.AddField(
            model_name='shipmentcostings',
            name='applied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='shipmentcostings',
            name='charge_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='shipmentcostings',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='shipmentcostings',
            name='payment_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_costings', to='operations.paymentsummary'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentmanifest',
            name='master_shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_shipment', to='operations.shipment', verbose_name='Master Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentmanifestbooking',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_shipments', to='operations.shipment', verbose_name='Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentmanifestbooking',
            name='shipment_items_loaded',
            field=models.ManyToManyField(blank=True, related_name='loaded_items', to='warehouse.handlingunit', verbose_name='Shipment Items Loaded'),
        ),
        migrations.AddField(
            model_name='shipmentmanifestbooking',
            name='shipment_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_bookings', to='operations.shipmentmanifest', verbose_name='Shipment Manifest'),
        ),
        migrations.AddField(
            model_name='shipmentmanifesthouse',
            name='shipment_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='operations.shipmentmanifest', verbose_name='Shipment Manifest'),
        ),
        migrations.AddField(
            model_name='shipmentmanifesthouse',
            name='shipment_manifest_booking',
            field=models.ManyToManyField(blank=True, related_name='manifest_houses', to='operations.shipmentmanifestbooking', verbose_name='Shipment Manifest Bookings'),
        ),
        migrations.AddField(
            model_name='shipmentmanifestbooking',
            name='house_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_bookings', to='operations.shipmentmanifesthouse', verbose_name='House Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentnote',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='shipmentnote',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentnote',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentpackages',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='shipmentpackages',
            name='mass_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pkg_unit_mass', to='master.unitofmeasurement', verbose_name='Unit of Mass/Weight'),
        ),
        migrations.AddField(
            model_name='shipmentpackages',
            name='package_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pkg_unit_length', to='master.unitofmeasurementlength', verbose_name='Unit of Length'),
        ),
        migrations.AddField(
            model_name='shipmentpackages',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_packages', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentpackages',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmenttransportinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='shipmenttransportinfo',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_info', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmenttransportinfo',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentwaybillfreightinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='shipmentwaybillfreightinfo',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_info', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentwaybillfreightinfo',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
