# Generated by Django 5.2.9 on 2026-02-05 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('actors', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingagency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agency', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='bookingagency',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='bookingagency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='bookingagency',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrier',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agency', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_created_for', to='master.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_salesman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='actors.customer'),
        ),
        migrations.AddField(
            model_name='customerperson',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='actors.customer'),
        ),
        migrations.AddField(
            model_name='customsagent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='customsagent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agency', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='customsagent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='customsagent',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='customsagent',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='designation',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='actors.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='actors.designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='parent_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_employees', to='actors.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbookingagency',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='created_for',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='salesman',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsagent',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.department'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='parent_employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.employee'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='booking_agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.bookingagency'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.carrier'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.customer'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='customs_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.customsagent'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.department'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='designation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.designation'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.employee'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.branch'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='user_add',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='booking_agency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.bookingagency'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='carrier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.carrier'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.customer'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='customs_agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.customsagent'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.department'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='designation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.designation'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.employee'),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agency', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='master.branch'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_categories', to='master.masterdata'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_add',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainactor',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_actor', to='actors.vendor'),
        ),
        migrations.AddField(
            model_name='historicalmainactor',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='actors.vendor'),
        ),
        migrations.AddIndex(
            model_name='bookingagency',
            index=models.Index(fields=['name'], name='actors_book_name_655f45_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagency',
            index=models.Index(fields=['transportation_mode'], name='actors_book_transpo_d7fa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagency',
            index=models.Index(fields=['branch'], name='actors_book_branch__8ea21f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingagency',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'transportation_mode'), name='uniq_bookingagency_branch_name_mode'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['name'], name='actors_carr_name_03c699_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['transportation_mode'], name='actors_carr_transpo_85e898_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['branch'], name='actors_carr_branch__002a90_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'transportation_mode'), name='uniq_carrier_branch_name_mode'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='actors_cust_custome_ceb1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mobile_no'], name='actors_cust_mobile__0a3cac_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch'], name='actors_cust_branch__c473c6_idx'),
        ),
        migrations.AddIndex(
            model_name='customsagent',
            index=models.Index(fields=['name'], name='actors_cust_name_0a94ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customsagent',
            index=models.Index(fields=['mobile'], name='actors_cust_mobile_f690e6_idx'),
        ),
        migrations.AddIndex(
            model_name='customsagent',
            index=models.Index(fields=['branch'], name='actors_cust_branch__dc571f_idx'),
        ),
        migrations.AddConstraint(
            model_name='customsagent',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_customsagent_branch_name'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='actors_depa_name_0ef8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['branch'], name='actors_depa_branch__daf838_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_department_branch_name'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['name'], name='actors_desi_name_7b5845_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['branch'], name='actors_desi_branch__0423b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_designation_branch_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'last_name'], name='actors_empl_first_n_3aaebd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['mobile_no'], name='actors_empl_mobile__e3fee5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['primary_email'], name='actors_empl_primary_3f1341_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='actors_empl_branch__1993de_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('branch', 'primary_email'), name='uniq_employee_branch_primary_email'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='actors_vend_name_502679_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['trn'], name='actors_vend_trn_67ae52_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['account_no'], name='actors_vend_account_45fc25_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['branch'], name='actors_vend_branch__882d78_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_vendor_branch_name'),
        ),
        migrations.AddIndex(
            model_name='mainactor',
            index=models.Index(fields=['branch', 'actor_type'], name='actors_main_branch__d6dae1_idx'),
        ),
        migrations.AddIndex(
            model_name='mainactor',
            index=models.Index(fields=['branch', 'display_name'], name='actors_main_branch__317907_idx'),
        ),
    ]
