# Generated by Django 5.2.9 on 2026-02-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='actor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_record', to='actors.mainactor'),
        ),
    ]
