# Generated by Django 5.2.9 on 2026-01-26 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccounts',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='historicalchartofaccounts',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Account Code'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccounts',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uniq_coa_code_per_branch'),
        ),
    ]
