# Generated by Django 5.2.9 on 2026-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_bankaccounts_code_alter_chartofaccounts_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='historicalchartofaccounts',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code'),
        ),
    ]
