# Generated by Django 5.2.9 on 2026-01-31 11:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_chartofaccounts_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Balance'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccounts',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Balance'),
        ),
    ]
