# Generated by Django 5.2.9 on 2026-01-31 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_bankaccounts_opening_balance_and_more'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccounts',
            name='uniq_bank_code_per_branch_nonnull_nonempty',
        ),
        migrations.AddConstraint(
            model_name='bankaccounts',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uniq_bank_code_per_branch'),
        ),
    ]
