# Generated by Django 5.2.9 on 2026-01-15 16:10

import decimal
import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_remove_bankaccounts_uniq_bank_code_per_branch_nonnull_nonempty_and_more"),
        ("actors", "0002_initial"),
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_system_generated", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, verbose_name="Account Name")),
                ("source", models.CharField(choices=[("coa", "Chart of Accounts"), ("bank", "Bank Account"), ("actor", "Actor")], max_length=20, verbose_name="Source")),
                ("balance", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("actor", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="account_record", to="actors.mainactor")),
                ("bank_account", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="account_record", to="accounting.bankaccounts")),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_branch", to="master.branch")),
                ("chart_account", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="account_record", to="accounting.chartofaccounts")),
                ("user_add", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_created", related_query_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "indexes": [
                    models.Index(fields=["source"], name="accounts_source_idx"),
                    models.Index(fields=["name"], name="accounts_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAccounts",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("active", models.BooleanField(default=True)),
                ("is_system_generated", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, verbose_name="Account Name")),
                ("source", models.CharField(choices=[("coa", "Chart of Accounts"), ("bank", "Bank Account"), ("actor", "Actor")], max_length=20, verbose_name="Source")),
                ("balance", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
            ],
            options={
                "verbose_name": "historical Account",
                "verbose_name_plural": "historical Accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
